server:
  port: 9199
spring:
  datasource:
    url: jdbc:mysql://47.112.186.155:3306/minimall
    username: root
    password: M2M123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true